# Generated by Django 5.2.7 on 2025-10-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_on_vacations',
            field=models.BooleanField(default=False),
        ),
    ]
